---
- name: Run OpenShift Applier
  hosts: local
  gather_facts: no
  vars:
    ci_cd_namespace: coo-ci-cd
    dev_namespace: coo-dev
    test_namespace: coo-test
  roles:
    - openshift-applier/roles/openshift-applier
