---
- name: Run OpenShift Applier
  hosts: local
  gather_facts: no
  vars:
    ci_cd_namespace: vue-booster-ci-cd
    dev_namespace: vue-booster-dev
    test_namespace: vue-booster-test
  roles:
    - openshift-applier/roles/openshift-applier
